PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX bd: <http://www.bigdata.com/rdf#>
SELECT ?LEI ?country
        WHERE {
             FILTER contains(?LEI, "529900PM64WH8AF1E917")
            ?company wdt:P1278  ?LEI ;
                     wdt:P17    ?country .
        SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
      }
